namePrefix: production-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    variant: production
patches:
- path: deployment.yaml
- path: config-map.yaml
