apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-example
  namespace: openshift-gitops
spec:
  destination:
    namespace: kustomize-example
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argo
    repoURL: https://github.com/hseligson1/kustomize-gitops-example.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
